blank_issues_enabled: false

contact_links:
  - name: ğŸ“˜ Documentation eTix iOS
    url: https://github.com/Nourdine84/etix-ios/wiki
    about: Consulte la documentation avant de crÃ©er un ticketÅ“blank_issues_enabled: false

contact_links:
  - name: eTix iOS â€“ CrÃ©er un ticket
    url: https://github.com/Nourdine84/etix-ios/issues/new/choose
    about: Utilisez un template pour crÃ©er une issue iOS
