blank_issues_enabled: false

contact_links:
  - name: eTix iOS – Créer un ticket
    url: https://github.com/Nourdine84/etix-ios/issues/new/choose
    about: Utilisez un template pour créer une issue iOS
